/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetTime */

#ifndef _Included_GetTime
#define _Included_GetTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetTime
 * Method:    getTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GetTime_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
